config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('pollsplus/', include('pollsplus.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('accounts/', include('accounts.urls',  namespace='accounts'))
]

app_name = 'polls'

pollsplus/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.posts, name='posts'),
    path('edit/<int:post_id>', views.edit, name='edit'),
    path('posts/<int:post_id>/comments/', views.comments, name='comments'),
    path('posts/<int:post_id>/comments/add/', views.addComment, name='addcomments'),
    path('posting/', views.posting, name='posting'),
    path('posting/upload/', views.upload, name='upload'),
    path('accounts/', include('accounts.urls',  namespace='accounts'))
]

app_name = 'pollsplus'

pollsplus/models.py
import string
from random import choice
from django.db import models

def user_path(instance, filename):
  pid = ''.join([choice(string.ascii_letters) for _ in range(8)])
  extension = filename.split('.')[-1]
  return f'{pid}.{extension}'
  
class Post(models.Model):
    # id : 자동 생성
    title_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(verbose_name='published date', auto_now_add=True)   # 자동으로 현재 시간 입력
    writer = models.CharField(max_length=20)    # 로그인 된 정보를 가져와야 할듯
    contents_text = models.TextField()  # TextField : 다중 행 크기 조절 가능 입력, CharField : 단일 라인 입력
    file = models.ImageField(upload_to=user_path)

    def __str__(self):
        return self.title_text


class Comment(models.Model):
    # id : 자동 생성
    # FK는 항상 다른 테이블의 PK로 연결되므로 클래스만 지정하면 됨
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(verbose_name='published date', auto_now_add=True)
    writer = models.CharField(max_length=20)
    contents_text = models.TextField()

    def __str__(self):
        return self.contents_text

pollsplus/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ('title_text', 'file')

  def __init__(self, *args, **kwargs):
    super(PostForm, self).__init__(*args, **kwargs)
    self.fields['file'].required = True

pollsplus/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Post, Comment
from .forms import PostForm


def index(request):
    if request.user.is_authenticated:
        return render(request, 'pollsplus/index.html', {'username': request.user.username})
    return render(request, 'pollsplus/index.html')


# 게시글 보기
def posts(request):
    latest_post_list = Post.objects.all().order_by('-pub_date')[:10]
    username = ""

    if request.user.is_authenticated:
        username = request.user.username

    if request.method == "POST":
        id = request.POST.get("id", "")
        post = Post.objects.all().filter(id=id)
        post.delete()
        return redirect("pollsplus:posts")

    context = {'latest_posts': latest_post_list, 'username': username}
    return render(request, 'pollsplus/posts.html', context)


# 댓글 달기
def comments(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user.is_authenticated:
        return render(request, 'pollsplus/comments.html', {'post': post, 'username': request.user.username})
    return render(request, 'pollsplus/comments.html', {'post': post})


# 댓글 작성, 업로드
def addComment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    try:
        writer = request.POST['writer']
        contents = request.POST['contents']
    except KeyError:
        return render(request, 'pollsplus/comments.html', {
            'post': post,
            'error_message': 'Upload is not successful. Please try again.'
        })
    comment = Comment(writer=writer, contents_text=contents)
    comment.post = post
    comment.save()
    return  HttpResponseRedirect(reverse('pollsplus:comments', args=(post.id, )))


# 게시글 작성창
def posting(request):
    if request.user.is_authenticated:
        return render(request, 'pollsplus/posting.html', {'username': request.user.username})
    return render(request, 'pollsplus:posts')


# 작성된 게시글 업로드
def upload(request):
    try:
        title_text = request.POST['title_text']
        contents = request.POST['contents']
        writer = request.POST['writer']

        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.title_text = title_text
            post.writer = writer
            post.contents = contents
            post.save()
        else:
            post = Post(title_text=title_text, writer=writer, contents_text=contents)
            post.save()
    except KeyError:
        return render(request, 'pollsplus/posting.html',
                      {'error_message': 'Upload is not successful. Please try again.'})

    return HttpResponseRedirect(reverse('pollsplus:posts', args=()))


def edit(request, post_id):
    post = Post.objects.get(id=post_id)

    if request.method == "POST":
        post.title_text = request.POST.get("title_text", "")
        post.writer = request.POST.get("writer", "")
        post.contents_text = request.POST.get("contents", "")
        post.save()
        return HttpResponseRedirect(reverse('pollsplus:posts'))

    if request.user.is_authenticated:
        return render(request, 'pollsplus/edit.html', {'post': post, 'username': request.user.username})
    else:
        return redirect('pollsplus:posts')

pollsplus/templates/pollsplus/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{% static 'pollsplus/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pollsplus/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pollsplus/_bootswatch.scss' %}">
</head>
<body class style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="navbarColor02" style="">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/pollsplus/">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/pollsplus/posts">Posts</a>
            </li>
            {% if username %}
            <li class="nav-item">
                <a class="nav-link" href="/pollsplus/posting">Create Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/polls/accounts/signout">Logout, {{ username }}</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="/polls/accounts/signin">SignIn</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/polls/accounts/signup">SignUp</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% block content %}
    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

pollsplus/templates/pollsplus/comments.html
{% extends 'pollsplus/base.html' %}

{% block content %}

{% if post %}
<h2>{{ post.title_text }}</h2>
{% if error_message %} <p><strong>{{ error_messege }}</strong></p> {% endif %}
<ul class="list-group list-group-flush">
    {% for comment in post.comment_set.all %}
    <li class="list-group-item">{{ comment.writer }} - {{ comment.contents_text }} ({{ comment.pub_date }})</li>
    {% endfor %}
</ul>
<form action="{% url 'pollsplus:addcomments' post.id %}" method="post">{% csrf_token %}
    {% if username %}
    <div class="form-group">
        <label class="col-form-label" for="inputDefault">Writer</label>
        <input type="text" class="form-control" placeholder="Default input" id="inputDefault" name="writer" required readonly value="{{ username }}">
    </div>
    {% else %}
    <div class="form-group">
        <label class="col-form-label" for="inputDefault">Writer</label>
        <input type="text" class="form-control" placeholder="Default input" id="inputDefault" name="writer" required placeholder="작성자">
    </div>
    {% endif %}
    <label class="col-form-label" for="inputContent">Content</label>
    <textarea class="form-control" id="inputContent" rows="3" name="contents"></textarea>
    <br>
    <input type="submit" class="btn btn-primary" value="submit">
</form>
{% else %}
<p>Comments are not exist</p>
{% endif %}
{% endblock %}

pollsplus/templates/pollsplus/edit.html
{% extends 'pollsplus/base.html' %}

{% block content %}
<br>
<h1>Edit Post</h1>

<form  method="post" enctype="multipart/form-data" novalidate>{% csrf_token %}{{ form.as_p }}
    <div class="form-group">
        <label class="col-form-label" for="inputTitle">Title</label>
        <input type="text" class="form-control" placeholder="Default input" id="inputTitle" name="title_text" required placeholder="제목" value="{{ post.title_text }}">
    </div>
    {% if username %}
    <div class="form-group">
        <label class="col-form-label" for="inputDefault">Writer</label>
        <input type="text" class="form-control" placeholder="Default input" id="inputDefault" name="writer" required readonly value="{{ username }}">
    </div>
    {% else %}
    <div class="form-group">
        <label class="col-form-label" for="inputDefault">Writer</label>
        <input type="text" class="form-control" placeholder="Default input" id="inputDefault" name="writer" required placeholder="작성자">
    </div>
    {% endif %}
    <div class="form-group">
        <label class="col-form-label" for="inputContent">Content</label>
        <textarea class="form-control" id="inputContent" rows="3" name="contents"></textarea>
    </div>

    Photos : <input type="file" name="file"><br>
    <br>
    <input type="submit" class="btn btn-primary" value="submit">
</form>
{% endblock %}

pollsplus/templates/pollsplus/index.html
{% extends 'pollsplus/base.html' %}

{% block content %}
<br>
<div class="col-lg-12">
    <div class="jumbotron">
        <h1 class="display-3">Simple Cafe!</h1>
        <p class="lead"> 간단하게 자신의 글과 사진을 공유하세요! </p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="/polls/accounts/signup" role="button">회원가입</a>
            <a class="btn btn-primary btn-lg" href="/pollsplus/posts" role="button">포스트</a>
        </p>
    </div>
</div>

{% endblock %}

pollsplus/templates/pollsplus/posting.html
{% extends 'pollsplus/base.html' %}

{% block content %}

<form action="{% url 'pollsplus:upload' %}" method="post" enctype="multipart/form-data" novalidate>{% csrf_token %}{{ form.as_p }}
    <div class="form-group">
        <label class="col-form-label" for="inputTitle">Title</label>
        <input type="text" class="form-control" placeholder="Default input" id="inputTitle" name="title_text" required placeholder="제목">
    </div>
    {% if username %}
    <div class="form-group">
        <label class="col-form-label" for="inputDefault">Writer</label>
        <input type="text" class="form-control" placeholder="Default input" id="inputDefault" name="writer" required readonly value="{{ username }}">
    </div>
    {% else %}
    <div class="form-group">
        <label class="col-form-label" for="inputDefault">Writer</label>
        <input type="text" class="form-control" placeholder="Default input" id="inputDefault" name="writer" required placeholder="작성자">
    </div>
    {% endif %}
    <label class="col-form-label" for="inputContent">Content</label>
    <textarea class="form-control" id="inputContent" name="contents" rows="3" required placeholder="내용을 입력하세요."></textarea>
    Photos : <br><input type="file" name="file"><br> <br>
    <input class="btn btn-primary" type="submit" value="등록">
</form>

{% endblock %}

pollsplus/templates/pollsplus/posts.html
{% extends 'pollsplus/base.html' %}

{% block content %}
<br>
{% if latest_posts %}
{% for post in latest_posts %}
<div class="bs-component">
    <div class="card mb-3">
        <h3 class="card-header">{{ post.title_text }}</h3>
        <div class="card-body">
            <h5 class="card-title">Date : {{ post.pub_date }}</h5>
            <h6 class="card-subtitle text-muted">Writer : {{ post.writer }}</h6>
        </div>

        {% if post.file %}
        <div>
            <img src="{{ post.file.url }}" width="100%" height="500px" style="object-fit: cover;"  alt=""/>
        </div>
        {% endif %}

        <div class="card-body">
            <p class="card-text">{{ post.contents_text|linebreaks }}</p>
        </div>

        <ul class="list-group list-group-flush">
            {% for comment in post.comment_set.all %}
            <li class="list-group-item">{{ comment.writer }} - {{ comment.contents_text }}</li>
            {% endfor %}
        </ul>

        {% if username == post.writer %}
        <ul>
            <form method="POST" action="{% url 'pollsplus:posts' %}">
                {% csrf_token %}
                <input type="text" name="id" style="display: none;" value="{{ post.id }}">
                <input class="btn btn-primary btn-lg" type="submit" value="삭제">
                <a class="btn btn-primary btn-lg" href="/pollsplus/edit/{{ post.id }}" role="button">수정하기</a>
            </form>
        </ul>
        {% endif %}

        <div class="card-body">
            <a href="/pollsplus/posts/{{ post.id }}/comments" class="card-link">댓글달기</a>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<p>Posts are not exist</p>
{% endif %}

{% endblock %}